/**
 *
 * $Id$
 */
package radioTeste.validation;

import javax.xml.datatype.XMLGregorianCalendar;

import radioTeste.CarrierFreq;
import radioTeste.OpRole;
import radioTeste.SampleSignal;
import radioTeste.SampleValue;
import radioTeste.Security;

/**
 * A sample validator interface for {@link radioTeste.LogEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LogEntryValidator {
	boolean validate();

	boolean validateSignal(SampleSignal value);

	boolean validateTimeStamp(int value);

	boolean validateTimeStamp(XMLGregorianCalendar value);

	boolean validateCarrierfreq(CarrierFreq value);

	boolean validateOprole(OpRole value);

	boolean validateSecurityLevel(Security value);

	boolean validateSampleValue(SampleValue value);
}
