/**
 *
 * $Id$
 */
package radioTeste.validation;

import radioTeste.LogEntry;
import radioTeste.OperationalRole;

/**
 * A sample validator interface for {@link radioTeste.OpRole}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OpRoleValidator {
	boolean validate();

	boolean validateRole(OperationalRole value);

	boolean validateLogentry(LogEntry value);
}
